import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {ContentCreatorsProvider} from "@/app/_providers/ContentCreatorsProvider";
import { GoogleAnalytics } from '@next/third-parties/google'
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import {Header} from "@/app/_components/Header";
import TopBanner from "@/app/_components/TopBanner";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ContentCreatorsProvider>
          <TopBanner />
          <Header />
          {children}
        </ContentCreatorsProvider>
      </body>
      <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID!} />
    </html>
  );
}
